const CACHE = 'machitalk-v1.10.1';
const SHELL = ['./', './index.html', './css/app.css?v=1.10.1', './js/app.js?v=1.10.1', './js/scene-engine.js', './js/speech.js', './js/evaluator.js', './js/attempts.js', './js/effects.js', './js/avatar.js', './js/storage.js', './data/scene-registry.json', './data/avatar-registry.json', './assets/avatar/aiko/neutral.webp', './assets/avatar/aiko/speaking.webp', './assets/avatar/aiko/listening.webp', './assets/avatar/aiko/encouraging.webp', './assets/avatar/aiko/pleased.webp', './assets/avatar/aiko/delighted.webp', './assets/avatar/aiko/celebrating.webp', './assets/avatar/aiko/thrilled.webp', './assets/avatar/linnea/neutral.webp', './assets/avatar/linnea/speaking.webp', './assets/avatar/linnea/listening.webp', './assets/avatar/linnea/encouraging.webp', './assets/avatar/linnea/pleased.webp', './assets/avatar/linnea/delighted.webp', './assets/avatar/linnea/celebrating.webp', './assets/avatar/linnea/thrilled.webp', './assets/avatar/koharu/neutral.jpg', './assets/avatar/koharu/speaking.webp', './assets/avatar/koharu/listening.webp', './assets/avatar/koharu/encouraging.webp', './assets/avatar/koharu/pleased.webp', './assets/avatar/koharu/delighted.webp', './assets/avatar/koharu/celebrating.webp', './assets/avatar/koharu/thrilled.webp', './assets/avatar/aiko/wardrobe/station.webp', './assets/avatar/aiko/wardrobe/restaurant.webp', './assets/avatar/aiko/wardrobe/service.webp', './assets/avatar/aiko/wardrobe/bus.webp', './assets/avatar/aiko/wardrobe/cafe.webp', './assets/avatar/aiko/wardrobe/hotel.webp', './assets/avatar/aiko/wardrobe/pharmacy.webp', './assets/avatar/linnea/wardrobe/station.webp', './assets/avatar/linnea/wardrobe/restaurant.webp', './assets/avatar/linnea/wardrobe/service.webp', './assets/avatar/linnea/wardrobe/bus.webp', './assets/avatar/linnea/wardrobe/cafe.webp', './assets/avatar/linnea/wardrobe/hotel.webp', './assets/avatar/linnea/wardrobe/pharmacy.webp', './assets/avatar/koharu/wardrobe/station.webp', './assets/avatar/koharu/wardrobe/restaurant.webp', './assets/avatar/koharu/wardrobe/service.webp', './assets/avatar/koharu/wardrobe/bus.webp', './assets/avatar/koharu/wardrobe/cafe.webp', './assets/avatar/koharu/wardrobe/hotel.webp', './assets/avatar/koharu/wardrobe/pharmacy.webp', './manifest.json', './assets/icons/icon-192.png', './assets/icons/icon-512.png'];
self.addEventListener('install', event => {
  event.waitUntil(caches.open(CACHE).then(cache => cache.addAll(SHELL)).then(() => self.skipWaiting()));
});
self.addEventListener('activate', event => {
  event.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(key => key.startsWith('machitalk-') && key !== CACHE).map(key => caches.delete(key)))).then(() => self.clients.claim()));
});
self.addEventListener('fetch', event => {
  if (event.request.method !== 'GET' || new URL(event.request.url).origin !== self.location.origin) return;
  event.respondWith(fetch(event.request, { cache: 'no-store' }).then(response => {
    if (response.ok) { const copy = response.clone(); caches.open(CACHE).then(cache => cache.put(event.request, copy)); }
    return response;
  }).catch(() => caches.match(event.request)));
});
